name: Mirror

on:
  workflow_dispatch:

  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: docker
    steps:
    - uses: actions/checkout@v4

    - uses: https://git.paynepride.com/nic/homelab-mono/devops/ci/forgejo-actions/sanitized-github-mirror@main
      with:
        remove: ""
        github_repo: pypeaday/DigitalHarbor
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_FORGEJO_MIRROR_BOT }}
